### ISSUE TITLE
v9.0.0 cyber_channel list报错

### ISSUE THREAD

**Issue by XuFlag** [minhanghuang/CyberRT#55]
### 环境
vmware + ubuntu22.04

### 工程
v9.0.0

### 问题
运行cyber_channel list 报错`E0311 18:15:54.413359 103703 py_cyber.cc:46] []cyber_py_init:PyArg_ParseTuple failed!`

### 详细信息

```
kada@ubuntu:~/Desktop/training/CyberRT/build$ cyber_channel list
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0311 18:15:54.395574 103703 class_loader_utility.h:79] []registerclass:Circle,Base,
I0311 18:15:54.395773 103703 class_loader_utility.h:79] []registerclass:Rect,Base,
I0311 18:15:54.395802 103703 class_loader_utility.h:79] []registerclass:Triangle,Base,
I0311 18:15:54.395824 103703 class_loader_utility.h:79] []registerclass:Star,Base,
I0311 18:15:54.395849 103703 class_loader_utility.h:79] []registerclass:Apple,Base,
I0311 18:15:54.395874 103703 class_loader_utility.h:79] []registerclass:Pear,Base,
I0311 18:15:54.395895 103703 class_loader_utility.h:79] []registerclass:Banana,Base,
I0311 18:15:54.395908 103703 class_loader_utility.h:79] []registerclass:Peach,Base,
E0311 18:15:54.413359 103703 py_cyber.cc:46] []cyber_py_init:PyArg_ParseTuple failed!
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kada/Desktop/training/CyberRT/build/bin/cyber/tools/cyber_channel/cyber_channel", line 398, in <module>
    cyber.init()
  File "/home/kada/Desktop/training/CyberRT/build/lib/python3.10/site-packages/cyber/python/cyber_py3/cyber.py", line 56, in init
    return _CYBER.py_init(module_name)
SystemError: <built-in function py_init> returned a result with an exception set
```

**Comment by minhanghuang** [comment]
Hi @XuFlag 这是因为`Python3.9`的原因, 相关问题 #25 
解决方法: 修改`cyber/python/internal/py_cyber.cc`
```Python
#define PY_SSIZE_T_CLEAN
#include <Python.h>
```

[fda46f74d96ac7af9a8251564840c2330bb39771](https://github.com/minhanghuang/CyberRT/commit/fda46f74d96ac7af9a8251564840c2330bb39771)

**Comment by XuFlag** [comment]
感谢大佬回复，按照解决方法修改，已正常运行~。期间也尝试过其他方法，切换python3.6去规避这个问题。

**Comment by 171930433** [comment]
> 感谢大佬回复，按照解决方法修改，已正常运行~。期间也尝试过其他方法，切换python3.6去规避这个问题。

@minhanghuang 是否可以根据python3的版本,用宏控制是否增加#define PY_SSIZE_T_CLEAN,目前的 v9.0.0版本,直接编译还是有这个问题
